export const estanques = [
  {
    id: "1",
    finca: "Finca La Reina",
    codigo: "EST-01",
    estado: "Activo",
    tipoEstanque: "tierra_semiintensivo",
    largo: "120",
    ancho: "80",
    profundidad: "1.2",
    fuenteAgua: "estero",
    especie: "litopenaeus_vannamei",
    fechaSiembra: "15/03/2026",
    fechaInicioEngorde: "05/04/2026",
    fechaMantenimiento: "20/06/2026",
    densidadSiembra: "12",
    precria: "si",
    metodoAlimentacion: "manual",
    proveedorAlimento: "Biomar",
    numeroAireadores: "4",
    tieneAlimentadorAutomatico: "no",
  },

  {
    id: "2",
    finca: "Finca La Reina",
    codigo: "EST-02",
    estado: "Engorde",
    tipoEstanque: "geomembrana",
    largo: "100",
    ancho: "60",
    profundidad: "1.5",
    fuenteAgua: "reservorio",
    especie: "litopenaeus_vannamei",
    fechaSiembra: "10/02/2026",
    fechaInicioEngorde: "01/03/2026",
    fechaMantenimiento: "15/06/2026",
    densidadSiembra: "18",
    precria: "si",
    metodoAlimentacion: "automatico",
    proveedorAlimento: "Skretting",
    numeroAireadores: "6",
    tieneAlimentadorAutomatico: "si",
  },

  {
    id: "3",
    finca: "Finca La Esperanza",
    codigo: "EST-03",
    estado: "Preparacion",
    tipoEstanque: "reservorio",
    largo: "150",
    ancho: "90",
    profundidad: "1.3",
    fuenteAgua: "golfo",
    especie: "litopenaeus_vannamei",
    fechaSiembra: "01/07/2026",
    fechaInicioEngorde: "",
    fechaMantenimiento: "28/06/2026",
    densidadSiembra: "10",
    precria: "no",
    metodoAlimentacion: "manual",
    proveedorAlimento: "Biomar",
    numeroAireadores: "2",
    tieneAlimentadorAutomatico: "no",
  },

  {
    id: "4",
    finca: "Finca El Manglar",
    codigo: "EST-04",
    estado: "Mantenimiento",
    tipoEstanque: "superintensivo",
    largo: "80",
    ancho: "50",
    profundidad: "1.8",
    fuenteAgua: "reservorio",
    especie: "litopenaeus_vannamei",
    fechaSiembra: "20/01/2026",
    fechaInicioEngorde: "15/02/2026",
    fechaMantenimiento: "28/06/2026",
    densidadSiembra: "25",
    precria: "si",
    metodoAlimentacion: "manual_automatico",
    proveedorAlimento: "Nicovita",
    numeroAireadores: "8",
    tieneAlimentadorAutomatico: "si",
  },

  {
    id: "5",
    finca: "Finca El Coral",
    codigo: "EST-05",
    estado: "Cosechado",
    tipoEstanque: "tierra_semiintensivo",
    largo: "110",
    ancho: "70",
    profundidad: "1.1",
    fuenteAgua: "estero",
    especie: "litopenaeus_vannamei",
    fechaSiembra: "12/12/2025",
    fechaInicioEngorde: "05/01/2026",
    fechaMantenimiento: "15/05/2026",
    densidadSiembra: "15",
    precria: "no",
    metodoAlimentacion: "manual",
    proveedorAlimento: "Biomar",
    numeroAireadores: "3",
    tieneAlimentadorAutomatico: "no",
  },
];